---
# ----------------------------------------------------------------------------------------------
# Script Name: tomcat-stop-Windows.yml
# Version: 1.0
# Author: Eric Lacroix
# Date: 05/09/2023
#
# Description: Stop Tomcat service.
#
# ----------------------------------------------------------------------------------------------

- name: Set Tomcat service startup mode to manual and ensure it is stopped
  ansible.windows.win_service:
    name: '{{service_name}}'
    start_mode: manual
    state: stopped

- name: Confirm Tomcat service is stopped
  ansible.windows.win_service_info:
    name: '{{service_name}}'
  register: service_info

- debug: 
    msg: "{{service_info.services[0].state}}"