#
# Inventory file for the pre-prod environment
#
#
all:
  hosts:
    ansible-control:
  children:
    vip:
      hosts:
        demo-public-vip:
    loadbalancers:
      hosts:
        demo-paz-lb:
        demo-apps-lb:
    webservers:
      hosts:
        demo-paz-apache-1:
        demo-paz-apache-2:
    appservers:
      hosts:
        demo-apps-tomcat-1:
        demo-apps-tomcat-2:
    tomcatservers:
      hosts:
        demo-apps-tcw-1:
        demo-apps-tcw-2: