#
# Inventory file for the pre-prod environment
#
# $Id$
# 
all:
  hosts:
    ansible-control:
  children:
    windowsservers:
      hosts:
        demo-apps-tcw-1:
        demo-apps-tcw-2:
    vip:
      hosts:
        demo-public-vip:
    appslb: 
      hosts:  
        demo-apps-lb:
    loadbalancers:
      hosts:
        demo-paz-lb:
        demo-apps-lb:
    webservers:
      hosts:
        demo-paz-apache-1:
        demo-paz-apache-2:
    appservers:
      hosts:
        demo-apps-tomcat-1:
        demo-apps-tomcat-2:
<<<<<<< HEAD
    brokerappserver:
      hosts:
        demo-mel-1:
=======
        demo-apps-tcw-1:
        demo-apps-tcw-2:
>>>>>>> lacroixe-tomcat-merge
