# file: infrastructure.yml
# 
# This playbook defines the IaC (Infrastructure as Code) component.  I kept this separate because it is NOT middleware.
# 
# Currently, we only setup load balancers
#
---
- name:  Deploy/Update Infrastructure (IaC)
  hosts: vip appslb
  become: "{{ true if ansible_system == 'Linux' else omit }}"
  roles:
  # push the host maps to the lb
  - role: common/push-host-map

  #- role: common/install-lb
  - role: common/motd 
    system_manager: james.benedict@ssc-spc.gc.ca
  
    # call role to install paz lb
  - role: infrastructure/loadbalancers
    lb_zone: paz
  
    # call role to install apps lb
  - role: infrastructure/loadbalancers
    lb_zone: apps

  # do we need this one ? TBD
  #- role: common/os-patching
  
  #- role: infrastructure/deploy-maintenance-page  

