---
# file: site.yml
# description: 
# The main deployment script
# call this script to deploy or update the application

#
# deploy/update web tier
#
- ansible.builtin.import_playbook: webservers.yml

#
# deploy/update application tier
#
- ansible.builtin.import_playbook: appservers.yml 

    