---
# file: start-tomcat.yml
#
# description: this playbook starts the tomcat servers at the app tier
#

- name: start tomcat
  hosts: appservers 
  #become: yes
  roles:

    # Call the role to stop tomcat
    # no parameters
    
  - role: operations/start-tomcat 