---
# file: stop-tomcat.yml
# 
# This playbook just stops tomcat, that's it!
#

- name:  Stop tomcat
  hosts: appservers windowsservers
  #become: yes
  roles:

    # Call the role to stop tomcat
    # no parameters
    
  - role: operations/stop-tomcat 
    become: "{{ true if ansible_system == 'Linux' else omit }}"
   