---
# file: webservers.yml
# 
# This playbook is responsible for the initial deployment of the web tier as well as applying any patches and changes
#

- name:  Deploy/Update Web Tier
  hosts: webservers 
  become: yes
  roles:

    # push any updates to the message of the day
    # parameters:
    #   system_manager - contact email listed in the motd
    #   specifying a parameter here will override anything specified in the defaults

  - role: common/motd 
    system_manager: james.benedict@ssc-spc.gc.ca

    # check for any package updates and launch patching tool
    # note: this application will always upgrade to the LATEST version of all packages
  - role: common/os-patching

    # since we don't have dns, we will need to manually create /etc/hosts
    # we will be using a variable to define the hosts
  - role: common/push-host-map

    # install and configure apache httpd
    # note: once apache is installed, it will be kept up-to-date by the os-patching role
  - role: webservers/setup-proxy

    # deploy/push static content: DISABLED
    # in the original project, we had a play to push static content that we were working on
    # that will be ported later
  #- role: webservers/static-content
