---
# Install Tomcat Server

- name: Install Tomcat Server
  hosts: tomcatservers
  tasks:
    - name: Create root directory
      ansible.windows.win_file:
        path: D:\ESERVICES
        state: directory
    
    - name: Create Apps\Tomcat subdirectory
      ansible.windows.win_file:
        path: D:\ESERVICES\Apps\Tomcat
        state: directory

    - name: Create Java subdirectory
      ansible.windows.win_file:
        path: D:\ESERVICES\Java
        state: directory

    - name: Create Software\Java subdirectory
      ansible.windows.win_file:
        path: D:\ESERVICES\Software\Java
        state: directory

    - name: Create Software\Tomcat subdirectory
      ansible.windows.win_file:
        path: D:\ESERVICES\Software\Tomcat
        state: directory

    # Preparing the Software
    # Copy Tomcat installation files from temporary location
    - name: Copy Tomcat installation files
      ansible.windows.win_copy:
        src: C:\Temp\OPENAM_TOMCAT_9.0.62/
        dest: D:\ESERVICES\Software\Tomcat
        remote_src: true

    # Create Java source directory based on version
    - name: Create Java source directory
      ansible.windows.win_file:
        path: D:\ESERVICES\Java\jdk1.8.0_333
        state: directory

    # Copy JAVA files from temporary location
    - name: Copy JAVA files
      ansible.windows.win_copy:
        src: C:\Temp\jdk1.8.0_333/
        dest: D:\ESERVICES\Java\jdk1.8.0_333
        remote_src: true

    # Launch the Tomcat Installer
    - name: Launch the Tomcat Installer
      ansible.windows.win_command:
        cmd: '"D:\ESERVICES\Software\Tomcat\install-openam.bat"'