---
#
# Call the appropriate deploy playbook, based on OS family
#
#- name: Add the OS specific variables from vars
#  include_vars: "{{ item }}"
#  with_first_found:
#    - "{{ ansible_distribution }}{{ ansible_distribution_major_version }}.yml"
#    - "{{ ansible_os_family }}.yml"
   

#- include_tasks: "motd-{{ ansible_os_family }}.yml"

- include_tasks: "{{ item }}"
  with_first_found:
    - files:
        - "motd-{{ ansible_os_family }}.yml"
      skip: true