---
# file: roles/appservers/deploy-war-helloworld/tasks/main.yml
#
# Call the appropriate deploy playbook, based on OS family
#
- name: Add the OS specific variables from vars
  include_vars: "{{ item }}"
  with_first_found:
    - rainbowunicorn.yml
    - "{{ ansible_distribution }}{{ ansible_distribution_major_version }}.yml"
    - "{{ ansible_os_family }}.yml"

- include_tasks: "deploy-war-{{ ansible_os_family }}.yml"
