---
# file: operations/stop-maintenance-mode/tasks/main.yml
#
# This will put the application back online
#

# modify file in NGINX to direct traffic to the PAZ servers
# don't know how to do that, never worked with NGINX before
#- name: stop maintenance mode