---
# file: operations/start-maintenance-mode/tasks/main.yml
#
# This will put the application in maintenance mode
#

# modify file in NGINX to redirect traffic to the maintenance page instead of the PAZ servers
# don't know how to do that, never worked with NGINX before
#- name: start maintenance mode
  
- name: start maintenance mode
  ansible.builtin.copy:
    src: /usr/share/nginx/html/maintenance-page.html
    dest: /usr/share/nginx/html/under-maintenance.html
    remote_src: yes