---
# ----------------------------------------------------------------------------------------------
# Script Name: tomcat-firewall-Windows.yml
# Version: 1.0
# Author: Eric Lacroix
# Date: 05/09/2023
#
# Description: Set Firewall Rules for Tomcat.
#
# ----------------------------------------------------------------------------------------------

- name: Set firewall rules for Tomcat
  win_firewall_rule:
    name: Allow Tomcat 8080
    localport: 8080
    action: allow
    direction: in
    protocol: tcp
    profiles: private
    state: present
    enabled: yes