# file: inventories/preprod/group_vars/all.yml
#
# This file contains variables that apply to ALL groups in the PREPROD environment
#

#
# env_name
#
# Specifies the name of the environment, current options are:
# DEV - local development
# PRE - PredProd
# PRD - Production
#

env_name: PRE # TODO: align with env_specific

#
# env_prefix is an env-specific prefix to hostnames, while env_domain is the registered domain, if any.
#
env_prefix: demo 
env_domain: 

# host_ips contains the IP Address and host/alias mappings for this environment
#

host_ips:
  - 192.168.2.164	ansible-1 {{env_prefix}}-paz-apache-1
  - 192.168.2.162	ansible-2 {{env_prefix}}-paz-apache-2
  - 192.168.2.168	ansible-3 {{env_prefix}}-apps-tomcat-1
  - 192.168.2.169	ansible-4 {{env_prefix}}-apps-tomcat-2
  - 192.168.2.170	ansible-5 {{env_prefix}}-apps-lb
  - 192.168.2.171	ansible-6 {{env_prefix}}-paz-lb
  - 192.168.2.61	{{env_prefix}}-apps-tcw-2
  - 192.168.2.60	{{env_prefix}}-apps-tcw-1


#
#  This contains the env-specific variable identifying the staging directory
#
staging_directory: "/Projects/Staging/CawJProject2Dep"
env_specific: "{{ staging_directory }}/Inventories/{{env_name}}"

#
# This variable defines the platform for the env
# valid values
# EDC - Endstate DataCenter (e.g VMs with LACMS)
# Legacy - typical VMs 
# LegNoDNS - VMs without DNS
# OCP - OpenShift
#
# hosting_platform
# valid values
# ESX
# AWS
# Azure
# OCP
#
env_type: "LegNoDNS"