---
#
# general vars
#
# These vars are basic config parms for the lb
#
lb_zone: paz 
lb_server_name: 

#
# listen vars
#
# these vars define the listener context, prot 
lb_listen_port: 80
lb_listen_location: /demo/

#
# target vars
#
# these variables define parameters related to the server pool
#
lb_target_context: 
lb_target_list: "{{ lb_paz }}"
lb_target_port: 80

lb_proxy_target: http://backends/demo/
