# file: inventories/preprod/group_vars/all.yml
#
ansible_user: ansiblead
ansible_password: Ans1bl3!
ansible_port: 5986
ansible_connection: winrm
ansible_winrm_transport: basic
ansible_winrm_server_cert_validation: ignore