---
# ----------------------------------------------------------------------------------------------
# Script Name: build-tomcat.yml
# Version: 1.0
# Author: Eric Lacroix
# Date: 17/08/2023
#
# Description: Build Tomcat server image and push to repository.
#
# ----------------------------------------------------------------------------------------------

- name: Build Tomcat server image
  hosts: ansible-control
  connection: local
  tasks:
    - name: Build container image
      containers.podman.podman_image:
        name: eservices
        path: ~/container/tomcat
        build:
          format: docker
        push: true
        tag: web-tomcat-dev
        username: gresident
        password: "Redhat@1-rule"
        push_args:
          dest: quay.io/gresident