---
# ----------------------------------------------------------------------------------------------
# Script Name: info-tomcat.yml
# Version: 1.0
# Author: Eric Lacroix
# Date: 17/08/2023
#
# Description: Retreive Tomcat service information.
#
# ----------------------------------------------------------------------------------------------

- name: Listing Tomcat service information
  hosts: tomcatservers
  tasks:
    - name: Get Tomcat service information
      ansible.windows.win_service_info:
        name: '{{service_name}}'
      register: service_info
    - debug: 
        msg: "Tomcat service {{service_name}} is {{service_info.services[0].state}}"