---
# ----------------------------------------------------------------------------------------------
# Script Name: install-tomcat.yml
# Version: 1.0
# Author: Eric Lacroix
# Date: 17/08/2023
#
# Description: Install Tomcat and all prerequisite components.
#
# ----------------------------------------------------------------------------------------------

- name: Install Tomcat
  hosts: tomcatservers
  tasks:
    # Set environment variables required to install Tomcat as a service
    - name: Set CATALINA Variable
      ansible.windows.win_path:
        state: present
        name: CATALINA_HOME
        elements: '{{tomcat_root}}\{{tomcat_home}}'
        scope: user

    - name: Set JAVA Runtime Environment Variable
      ansible.windows.win_path:
        state: present
        name: JRE_HOME
        elements: '{{tomcat_root}}\{{java_home}}\{{java_source}}\jre'
        scope: user
    
    - name: Set Tomcat Service Name Variable
      ansible.windows.win_path:
        state: present
        name: SERVICE_NAME
        elements: '{{service_name}}'
        scope: user

    - name: Set Tomcat Service PR Display Name Variable
      ansible.windows.win_path:
        state: present
        name: PR_DISPLAYNAME
        elements: '{{service_display_name}}'
        scope: user

    - name: Set Tomcat Service PR Description Name Variable
      ansible.windows.win_path:
        state: present
        name: PR_DESCRIPTION
        elements: '{{service_description}}'
        scope: user

    # Create the directory structure
    # Create root directory
    - name: Create root directory
      ansible.windows.win_file:
        path: '{{tomcat_root}}'
        state: directory

    - name: Create Java home subdirectory
      ansible.windows.win_file:
        path: '{{tomcat_root}}\{{java_home}}'
        state: directory

    - name: Create Tomcat home subdirectory
      ansible.windows.win_file:
        path: '{{tomcat_root}}\{{tomcat_home}}'
        state: directory
    
    - name: Create Tomcat backup subdirectory
      ansible.windows.win_file:
        path: '{{tomcat_root}}\{{tomcat_backup}}'
        state: directory

    - name: Create Java source directory based on version
      ansible.windows.win_file:
        path: '{{tomcat_root}}\{{java_home}}\{{java_source}}'
        state: directory

    # Preparing the Software
    # Copy Tomcat installation files from temporary location
    - name: Copy Tomcat installation files
      ansible.windows.win_copy:
        src: '{{install_source}}\{{tomcat_source}}/'
        dest: '{{tomcat_root}}\{{tomcat_home}}'
        remote_src: true

    # Copy JAVA files from temporary location
    - name: Copy JAVA files
      ansible.windows.win_copy:
        src: '{{install_source}}\{{java_source}}/'
        dest: '{{tomcat_root}}\{{java_home}}\{{java_source}}'
        remote_src: true

    # Launch the Tomcat Installer
    - name: Launch the Tomcat Installer
      ansible.windows.win_command:
        argv:
        - '{{tomcat_root}}\{{tomcat_home}}\bin\{{service_install_script}}'
        - install
    
    - name: Set Tomcat service startup mode to manual and ensure it is started
      ansible.windows.win_service:
        name: '{{service_name}}'
        start_mode: manual
        state: started