---
# Remove environment variables

- name: Remove environment variables
  hosts: tomcatservers
  tasks:
    - name: Remove CATALINA Variable
      ansible.windows.win_environment:
        state: absent
        name: CATALINA_HOME
        level: user

    - name: Remove JAVA Runtime Environment Variable
      ansible.windows.win_environment:
        state: absent
        name: JRE_HOME
        level: user
    
    - name: Remove Tomcat Service Name Variable
      ansible.windows.win_environment:
        state: absent
        name: SERVICE_NAME
        level: user
    
    - name: Remove Tomcat Service PR Display Name Variable
      ansible.windows.win_environment:
        state: absent
        name: PR_DISPLAYNAME
        level: user

    - name: Remove Tomcat Service PR Description Name Variable
      ansible.windows.win_environment:
        state: absent
        name: PR_DESCRIPTION
        level: user