---
# Remove Tomcat and all components

- name: Remove Tomcat
  hosts: tomcatservers
  tasks:
    ### Ensure the service is stopped before removing Tomcat ###
    - name: Stop Tomcat
      ansible.windows.win_service:
        name: TOMCAT9
        start_mode: manual
        state: stopped

    ### Remove Tomcat ###
    - name: Uninstall the Tomcat Service
      ansible.windows.win_command:
        argv:
        - D:\Tomcat\Tomcat\bin\tomcat9
        - //DS//Tomcat9

    ### Remove directory structure ###
    - name: Remove directory structure
      ansible.windows.win_file:
        path: D:\Tomcat
        state: absent

    ### Remove environment variables ###
    - name: Remove CATALINA Variable
      ansible.windows.win_environment:
        state: absent
        name: CATALINA_HOME
        level: user

    - name: Remove JAVA Runtime Environment Variable
      ansible.windows.win_environment:
        state: absent
        name: JRE_HOME
        level: user
    
    - name: Remove Tomcat Service Name Variable
      ansible.windows.win_environment:
        state: absent
        name: SERVICE_NAME
        level: user
    
    - name: Remove Tomcat Service PR Display Name Variable
      ansible.windows.win_environment:
        state: absent
        name: PR_DISPLAYNAME
        level: user

    - name: Remove Tomcat Service PR Description Name Variable
      ansible.windows.win_environment:
        state: absent
        name: PR_DESCRIPTION
        level: user