---
# Install Tomcat Server
#
- name: Install Tomcat Server
  hosts: tomcatservers
  tasks:
    - name: Create root directory
      ansible.windows.win_file:
        path: C:\ESERVICES
        state: directory
    
    - name: Create Apps\Tomcat directory
      ansible.windows.win_file:
        path: C:\ESERVICES\Apps\Tomcat
        state: directory

    - name: Create Java directory
      ansible.windows.win_file:
        path: C:\ESERVICES\Java
        state: directory

    - name: Create Software\Java directory
      ansible.windows.win_file:
        path: C:\ESERVICES\Software\Java
        state: directory

    - name: Create Software\Tomcat directory
      ansible.windows.win_file:
        path: C:\ESERVICES\Software\Tomcat
        state: directory

    # Preparing the Software
    # Copy Tomcat files
    - name: Copy Tomcat files
      ansible.windows.win_copy:
        src: C:\Temp\OPENAM_TOMCAT_9.0.62/
        dest: C:\ESERVICES\Software\Tomcat
        remote_src: true

    # Create Java source directory based on version
    - name: Create Java source directory
      ansible.windows.win_file:
        path: C:\ESERVICES\Java\jdk1.8.0_333
        state: directory

    # Copy JAVA files
    - name: Copy JAVA files
      ansible.windows.win_copy:
        src: C:\Temp\jdk1.8.0_333/
        dest: C:\ESERVICES\Java\jdk1.8.0_333
        remote_src: true